name: TWRP Build P205

on:
  workflow_dispatch: # Bisa kamu jalankan manual dari tab Actions
  push:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y bc bison build-essential curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop openjdk-11-jdk pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev
        sudo apt install -y python3

    - name: Repo init and sync
      run: |
        mkdir twrp && cd twrp
        curl https://storage.googleapis.com/git-repo-downloads/repo > repo
        chmod a+x repo
        ./repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1
        git clone https://github.com/yourusername/twrp_device_samsung_p205 device/samsung/p205
        ./repo sync -j$(nproc) --force-sync

    - name: Build TWRP
      run: |
        cd twrp
        source build/envsetup.sh
        lunch omni_p205-eng
        mka recoveryimage -j$(nproc)

        
    - name: Upload recovery image
      uses: actions/upload-artifact@v3
      with:
        name: recovery-image
        path: twrp/out/target/product/p205/recovery.img
